"use strict";

// Natural Earth keys used by the bundled client geography. Keep parity covered by tests.
const COUNTRY_CODES = new Set("AFG ALB DZA AGO ATA ARG ARM AUS AUT AZE BGD BLR BEL BLZ BEN BTN BOL BIH BWA BRA BRN BGR BFA BDI KHM CMR CAN CAF TCD CHL COL CRI HRV CUB CYP CZE COD DNK DJI DOM TLS ECU EGY SLV GNQ ERI EST SWZ ETH FLK FJI FIN FRA ATF GAB GEO DEU GHA GRC GRL GTM GIN GNB GUY HTI HND HUN ISL IND IDN IRN IRQ IRL ISR ITA CIV JAM JPN JOR KAZ KEN KOS KWT KGZ LAO LVA LBN LSO LBR LBY LTU LUX MDG MWI MYS MLI MRT MEX MDA MNG MNE MAR MOZ MMR NAM NPL NLD NCL NZL NIC NER NGA PRK MKD NOR OMN PAK PSX PAN PNG PRY CHN PER PHL POL PRT PRI QAT COG ROU RUS RWA SAU SEN SRB SLE SVK SVN SLB SOM SOL ZAF KOR SDS ESP LKA SDN SUR SWE CHE SYR TWN TJK TZA THA BHS GMB TGO TTO TUN TUR CYN TKM UGA UKR ARE GBR USA URY UZB VUT VEN VNM SAH YEM ZMB ZWE".split(" "));

module.exports = { COUNTRY_CODES };
